version: "3.2"
networks:
  test:
services:
  redis:
    container_name: redis
    image: "redis:latest"
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - test
  java:
    depends_on:
      - redis
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test


